from collections.abc import Callable
from contextlib import contextmanager
from typing import Any, overload

def njit(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def vectorize(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def set_num_threads(n: int) -> None: ...
@contextmanager
def objmode(*args: Any, **kwargs: Any) -> Any: ...
