# Minimal hand-written stub: only symbols this project imports.
# Extend here when a new numba top-level API is adopted; do not aim for completeness.
from collections.abc import Callable
from contextlib import contextmanager
from typing import Any

def njit(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def vectorize(*args: Any, **kwargs: Any) -> Callable[..., Any]: ...
def set_num_threads(n: int) -> None: ...
@contextmanager
def objmode(*args: Any, **kwargs: Any) -> Any: ...
