"""Regenerate tests/regression/reference_values.json from current code.

Runs the regression suite in record mode (``REGEN_REFS=1``): every
``assert_close(actual, ref[key])`` writes ``actual`` back under ``key`` (see
``tests/regression/conftest.py``), so the golden file is rebuilt from the exact
inputs the tests already define -- there is no separate input table to keep in
sync. A second normal pass then verifies the regenerated file.

Covers all ``reference_values.json`` keys (unit + e2e SE + cloud model). The
atom snapshot (``atom_reference_values.json``) is generated separately by
``scripts/gen_atom_reference.py``.

Run intentionally after a deliberate algorithm/constant change:

    uv run python scripts/gen_reference.py
"""

from __future__ import annotations

import os
from pathlib import Path
import subprocess
import sys

_REPO_ROOT = Path(__file__).resolve().parent.parent
_REG_DIR = _REPO_ROOT / "tests" / "regression"
# AtomLoad is regenerated by gen_atom_reference.py and asserts through
# _atom_serde (not assert_close), so it is excluded from both passes here.
_PYTEST_ARGS = ("-q", str(_REG_DIR), "--ignore", str(_REG_DIR / "test_reg_e2e_AtomLoad.py"))


def _pytest(regen: bool) -> int:
    env = {**os.environ, "REGEN_REFS": "1" if regen else "0"}
    return subprocess.run([sys.executable, "-m", "pytest", *_PYTEST_ARGS], env=env).returncode


def main() -> None:
    print("[1/2] record pass (REGEN_REFS=1) -> rewriting reference_values.json", flush=True)
    if _pytest(regen=True) != 0:
        sys.exit("record pass failed before the file could be written")

    print("[2/2] verify pass (normal mode)", flush=True)
    rc = _pytest(regen=False)
    if rc == 0:
        print("OK: regenerated reference_values.json passes the regression suite")
    sys.exit(rc)


if __name__ == "__main__":
    main()
