from typing import Generic, TypeVar

_T = TypeVar("_T")

class List(Generic[_T]):
    def append(self, item: _T) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _T: ...
    def __setitem__(self, index: int, value: _T) -> None: ...
    def __iter__(self): ...
